variable "region"                   {}
variable "aws_access_key"           {}
variable "aws_secret_key"           {}
variable "project_name"             {}
variable "username"                 {}
variable "email"                    {}
variable "team"                     {}
variable "policy_list"              {}
variable "groups"                   {}
variable "pgp_key"                  {}
