version: '3'
services:
#   flyway:
#     container_name: dev_flyway
#     image: flyway/flyway
#     command: -url=jdbc:mysql://mysql_db -schemas=dbname -user=root -password=password -connectRetries=60 migrate
#     volumes:
#       - ./.flyway:/flyway/sql
#     depends_on:
#       - mysql_db
#     networks:
#       main:
#         aliases:
#           - flyway
  mysql_db:
    container_name: dev_mysql_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: dbname
    volumes:
      - ./.db:/var/lib/mysql
      - ./.backup:/tmp/backup
    networks:
      main:
        aliases:
          - mysql_db
  adminer:
    container_name: dev_adminer
    image: adminer:4.7
    restart: always
    ports:
      - 8085:8080
    networks:
      main:
        aliases:
          - adminer
networks:
  main:

